pedido/urls.py
from django.urls import path
from . import views

app_name = 'pedido'

urlpatterns = [
    path(r'', views.PedidosView, name='index'),
]

producto/urls.py
from .views import ProductosIndex, ProductosVendidos, ProductosDisponibles
from django.urls import path

app_name = 'producto'

urlpatterns = [
    #path('detalles/<int:pk>/', ProductoDetalles.as_view(), name='productos-detalle'),
    path('index/', ProductosIndex.as_view(), name='productos-Index'),
    path('vendidos/', ProductosVendidos.as_view(), name='productos-vendidos'),
    path('disponibles/', ProductosDisponibles.as_view(), name='productos-disponibles'),
]

wildjay/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from producto.views import ProductosIndex

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', ProductosIndex.as_view()),
    path('productos/', include('producto.urls', namespace='producto')),
    path('pedidos/', include('pedido.urls', namespace='pedido')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pedido/models.py
from django.db import models

class Pedido(models.Model):
    nombre = models.CharField(max_length = 20, blank = False, null = False)
    email = models.EmailField(blank=False, null=False)
    asunto = models.CharField(max_length = 80, blank = False, null = False)
    mensaje = models.CharField(max_length = 500, blank = False, null = False)
    timestamp = models.DateTimeField(auto_now_add=True)

producto/models.py
import uuid
from django.db import models

def producto_image(instance, filename):
    return 'product_{0}/{1}/{2}'.format(instance.nombre, uuid.uuid4(), filename)


class Producto(models.Model):
    #Categorias
    CHAQUETA = 'CH'
    CAMISETA = 'CA'
    PANTALON = 'PA'
    ACCESORIO = 'AC'

    CATEGORIAS = (
        (CHAQUETA, 'Chaqueta'),
        (CAMISETA, 'Camiseta'),
        (PANTALON, 'Pantalon'),
        (ACCESORIO, 'Accesorio')

    )

    #Tallas
    TALLAS = (
        ('XXS', 'XXS'),
        ('XS', 'XS'),
        ('S', 'S'),
        ('M', 'M'),
        ('L', 'L'),
        ('XL', 'XL'),
        ('XXL', 'XXL'),
        ('XXXL', 'XXXL')
    )

    nombre = models.CharField(max_length=120, null=False, blank=False)
    precio = models.IntegerField(null=False, blank=False)
    stock = models.IntegerField(null=False, blank=False, default=0)
    descripcion = models.CharField(max_length=500)
    categoria = models.CharField(
        max_length=2,
        choices=CATEGORIAS,
        default=CHAQUETA
    )
    talla = models.CharField(
        max_length=5,
        choices=TALLAS,
        default='L',
        null=True,
        blank=True
    )
    imagen = models.ImageField(upload_to=producto_image, null=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'Producto {}'.format(self.nombre)

pedido/views.py
from django.shortcuts import render
from .models import Pedido
from django.http import HttpResponse

def PedidosView(request):
    if request.method == 'POST':
        pedido = Pedido()
        pedido.nombre = request.POST['nombre']
        pedido.email = request.POST['email']
        pedido.asunto = request.POST['asunto']
        pedido.mensaje = request.POST['mensaje']
        pedido.save()
        return HttpResponse('')

    return render(request, 'pedido/index.html', {})

producto/views.py
from .models import Producto
from django.views.generic.detail import DetailView
from django.shortcuts import render
from django.views.generic import TemplateView

#class ProductoDetalles(DetailView):


class ProductosIndex(TemplateView):
    model = Producto
    template_name = 'producto/index.html'

    def dispatch(self, *args, **kwargs):
        return super(ProductosIndex, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ProductosIndex, self).get_context_data(**kwargs)
        productos = Producto.objects.all()
        context['productos'] = productos
        return context



class ProductosVendidos(TemplateView):
    model = Producto
    template_name = 'producto/vendidos.html'

    def dispatch(self, *args, **kwargs):
        return super(ProductosVendidos, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ProductosVendidos, self).get_context_data(**kwargs)
        productos = Producto.objects.filter(stock=0)
        context['productos'] = productos
        return context

class ProductosDisponibles(TemplateView):
    model = Producto
    template_name = 'producto/disponibles.html'

    def dispatch(self, *args, **kwargs):
        return super(ProductosDisponibles, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ProductosDisponibles, self).get_context_data(**kwargs)
        productos = Producto.objects.exclude(stock=0)
        context['productos'] = productos
        return context

pedido/templates/pedido/index.html
{% extends "wildjay/plantilla.html" %}
{% load staticfiles %}

{% block titulo %}
    Pedidos
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <form id="form_pedido" class="col s12">
                {% csrf_token %}
                <div class="row center">
                    <br/>
                    <h5>FORMULARIO DE CONTACTO</h5>
                </div>
                <div class="input-field col s12 m6">
                    <input class="input-field" id="nombre" type="text" required/>
                    <label for="nombre">Nombre</label>
                </div>
                <div class="input-field col s12 m6">
                    <input class="input-field" id="email" type="email" required/>
                    <label for="email" data-error="wrong" data-success="right">Email</label>
                </div>
                <div class="input-field col s12">
                    <input class="input-field" id="asunto" type="text" required/>
                    <label for="asunto">Asunto</label>
                </div>
                <div class="input-field col s12">
                    <textarea class="materialize-textarea" id="mensaje" type="text" required></textarea>
                    <label for="mensaje">Mensaje</label>
                </div>
                <div class="row center">
                    <button class= "waves-effect waves-light btn deep-purple lighten-1" style="border: 1px solid black;" type="submit">Enviar</button>
                </div>
            </form>
        </div>
    </div>
    <div id= "rrss" class="row container">
        <div class="row center">
            <br/>
            <h5>REDES SOCIALES</h5>
        </div>
        <div class="col s12">
          <div class="col s6 m3 center">
              <a href="https://www.instagram.com/wildjaycustomshop/"><img src="{% static "img/ig.png" %}" alt="Instagram" style="height: 75px; width: 75px;"/></a>
          </div>
          <div class="col s6 m3 center">
              <a href="#"><img src="{% static "img/mail.png" %}" alt="email" style="height: 75px; width: 75px;"/></a>
          </div>
          <div class="col s6 m3 center">
              <a href="#"><img src="{% static "img/tw.png" %}" alt="twitter" style="height: 75px; width: 75px;"/></a>
          </div>
          <div class="col s6 m3 center">
              <a href="#"><img src="{% static "img/fb.png" %}" alt="facebook" style="height: 75px; width: 75px;"/></a>
          </div>
        </div>
      </div>
    <script>
        $(document).on('submit', '#form_pedido', function (event) {
            event.preventDefault()
            $.ajax({
               type: 'POST',
               url: '{% url 'pedido:index' %}',
               data: {
                   nombre: $('#nombre').val(),
                   email: $('#email').val(),
                   asunto: $('#asunto').val(),
                   mensaje: $('#mensaje').val(),
                   csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
               },
                success: function(){
                   Materialize.toast('¡Formulario enviado!', 2000);
                   $('#nombre').val('');
                   $('#email').val('');
                   $('#asunto').val('');
                   $('#mensaje').val('');
                },
                error: function () {
                    Materialize.toast('Error al enviar el formulario, ¡inténtalo de nuevo!', 2000);
                }
            });

        })
    </script>
{% endblock %}

producto/templates/producto/disponibles.html
{% extends "wildjay/plantilla.html" %}
{% load static %}

{% block titulo %}
    Disponibles
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            {% for producto in productos %}
                <div class="col s12 m4">
                    <div class="card">
                        <div class="card-image">
                            <img class="materialboxed" src="{{ producto.imagen.url }}" />
                        </div>
                        <div class="card-content">
                            <span class="card-title activator grey-text text-darken-4">
                                {{ producto.nombre }}<i class="material-icons right">add</i>
                                <div class="divider"></div>
                            </span>
                            <p>Precio: {{ producto.precio }}€</p>
                        </div>
                        <div class="card-reveal">
                            <span class="card-title grey-text text-darken-4">
                                {{ producto.nombre }}<i class="material-icons right">close</i>
                                <div class="divider"></div>
                            </span>
                            <p>{{ producto.descripcion }}</p>
                            <div class="divider"></div>
                            <p><b>Precio</b>: {{ producto.precio }}€</p>
                            <p><b>Talla</b>: {{ producto.talla }}</p>
                            <div class="divider"></div>
                            <span style="vertical-align: bottom; bottom: 20px; position: absolute; font-size: x-small;">
                                Si estás interesado en este producto contacta con nosotros usando el <a href="{% url 'pedido:index' %}">formulario de contacto </a>
                                o con un mensaje en cualquiera de nuestras <a href="/pedidos/#rrss">redes sociales</a>.
                            </span>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <script>
        $(document).ready(function() {
            $('.materialboxed').materialbox();
        });
    </script>
{% endblock %}

producto/templates/producto/index.html
{% extends "wildjay/plantilla.html" %}
{% load static %}

{% block titulo %}
    Inicio
{% endblock %}

{% block content %}
    <div class="section">
      <div class="row container">
        <h3 class="header">Presentación.</h3>
        <p class="grey-text text-darken-3 lighten-3">
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
            Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes,
            nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.
            Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu.
            In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.
            Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi.
            Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim.
            Aliquam lorem ante, dapibus in, viverra quis, feugiat.
        </p>
      </div>
    </div>
    <div class="parallax-container">
      <div class="parallax"><img src="{% static "img/girl.jpg" %}"></div>
    </div>
    <div class="section">
      <div class="row container">
        <h3 class="header">Info.</h3>
        <p class="grey-text text-darken-3 lighten-3">
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
            Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes,
            nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.
            Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu.
            In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.
            Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi.
            Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim.
            Aliquam lorem ante, dapibus in, viverra quis, feugiat.
        </p>
       </div>
    </div>
    <div class="parallax-container">
      <div class="parallax"><img src="{% static "img/eye.jpg" %}"></div>
    </div>
    <div class="section">
      <div class="row container">
          <br/>
          <div class="col s12">
              <div class="col s6 m3 center">
                  <a href="https://www.instagram.com/wildjaycustomshop/"><img src="{% static "img/ig.png" %}" alt="Instagram" style="height: 75px; width: 75px;"/></a>
              </div>
              <div class="col s6 m3 center">
                  <a href="#"><img src="{% static "img/mail.png" %}" alt="email" style="height: 75px; width: 75px;"/></a>
              </div>
              <div class="col s6 m3 center">
                  <a href="#"><img src="{% static "img/tw.png" %}" alt="twitter" style="height: 75px; width: 75px;"/></a>
              </div>
              <div class="col s6 m3 center">
                  <a href="#"><img src="{% static "img/fb.png" %}" alt="facebook" style="height: 75px; width: 75px;"/></a>
              </div>
          </div>
      </div>
    </div>
    <script>
    $(document).ready(function(){
        $('.parallax').parallax();
    });

    </script>
{% endblock %}

producto/templates/producto/vendidos.html
{% extends "wildjay/plantilla.html" %}
{% load static %}

{% block titulo %}
    Vendidos
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            {% for producto in productos %}
                <div class="col s12 m4">
                    <div class="card">
                        <div class="card-image">
                            <img class="materialboxed" src="{{ producto.imagen.url }}" />
                        </div>
                        <div class="card-content">
                            <span class="card-title activator grey-text text-darken-4">
                                {{ producto.nombre }}<i class="material-icons right">add</i>
                                <div class="divider"></div>
                            </span>
                            <p>Precio: <strike>{{ producto.precio }}€</strike></p>
                        </div>
                        <div class="card-reveal">
                            <span class="card-title grey-text text-darken-4">
                                {{ producto.nombre }}<i class="material-icons right">close</i>
                                <div class="divider"></div>
                            </span>
                            <p>{{ producto.descripcion }}</p>
                            <div class="divider"></div>
                            <p><b>Precio</b>: <strike>{{ producto.precio }}€</strike></p>
                            <p><b>Talla</b>: <strike>{{ producto.talla }}</strike></p>
                            <div class="divider"></div>
                            <span style="right: 5px; left: 25px; vertical-align: bottom; bottom: 20px; position: absolute; font-size: x-small;">
                                Sin stock. Para cualquier encargo contacta con nosotros usando el <a href="{% url 'pedido:index' %}">formulario de contacto </a>
                                o con un mensaje en cualquiera de nuestras <a href="/pedidos/#rrss">redes sociales</a>.
                            </span>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <script>
        $(document).ready(function() {
            $('.materialboxed').materialbox();
        });
    </script>
{% endblock %}

wildjay/templates/wildjay/footer.html
<footer class="page-footer light-green">
    <div class="footer-copyright">
        <div class="container center">
            © 2018 Copyright WildJay CustomShop
        </div>
    </div>
</footer>

wildjay/templates/wildjay/header.html
{% load static %}
<nav>
	<ul id="desplegable1" class="dropdown-content">
		<li><a href="{% url "producto:productos-disponibles" %}">Disponibles</a></li>
		<li><a href="{% url "producto:productos-vendidos" %}">Vendidos</a></li>
	</ul>
	<ul id="desplegable2" class="dropdown-content">
		<li><a href="{% url "producto:productos-disponibles" %}">Disponibles</a></li>
		<li><a href="{% url "producto:productos-vendidos" %}">Vendidos</a></li>
	</ul>
	<div class="nav-wrapper">
		<a href="{% url "producto:productos-Index" %}" class="brand-logo center" style="top: 5px;">
			<img class="circle" src="{% static "img/logo.jpg" %}" alt="logo" style="height: 65px; width: 65px;" />
		</a>
		<a href="#" data-activates="mobile-demo" class="button-collapse"><i
			class="material-icons">menu</i></a>

		<ul id="nav-mobile" class="left hide-on-med-and-down">
			<li><a href="{% url "producto:productos-Index" %}">Inicio</a></li>
			<li><a class="dropdown-button" href="#!"
				data-activates="desplegable1">Productos<i
					class="material-icons right">arrow_drop_down</i></a></li>
		</ul>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
			<li><a href="{% url "pedido:index" %}">Contacto</a></li>
		</ul>
		<ul class="side-nav" id="mobile-demo">
			<li><a href="{% url "producto:productos-Index" %}">Inicio</a></li>
			<li><a class="dropdown-button" href="#!"
				data-activates="desplegable2">Productos<i
					class="material-icons right">arrow_drop_down</i></a></li>
			<li><a href="{% url "pedido:index" %}">Contacto</a></li>
		</ul>
	</div>
	<script>
		$(document).ready(function() {
			$(".button-collapse").sideNav();
		});
	</script>
</nav>

wildjay/templates/wildjay/plantilla.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>WildJay - {% block titulo %}{% endblock %}</title>
    <link rel="shortcut icon" type="image/png" href="{% static "img/favicon.PNG" %}"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
	<link rel="stylesheet" href="{% static "css/materialize.min.css" %}" />
	<link rel="stylesheet" href="{% static "css/wildjay.css" %}" />
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
	<script type="text/javascript" src="{% static "js/materialize.min.js" %}"></script>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
<header>
    {% block menu %}
        {% include "wildjay/header.html" %}
    {% endblock %}
</header>
<main>

    {% block content %}
    {% endblock %}

</main>
<footer>
    {% block footer %}
        {% include "wildjay/footer.html" %}
    {% endblock %}
</footer>
</body>
</html>